# ----- ***Loading The Data*** -----

In [ ]:
!pip install statsbombpy

Collecting statsbombpy
  Downloading statsbombpy-1.14.0-py3-none-any.whl.metadata (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.7/63.7 kB 1.9 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from statsbombpy) (2.2.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from statsbombpy) (2.32.3)
Collecting requests-cache (from statsbombpy)
  Downloading requests_cache-1.2.1-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: inflect in /usr/local/lib/python3.11/dist-packages (from statsbombpy) (7.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from statsbombpy) (1.4.2)
Requirement already satisfied: more_itertools>=8.5.0 in /usr/local/lib/python3.11/dist-packages (from inflect->statsbombpy) (10.5.0)
Requirement already satisfied: typeguard>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from inflect->statsbombpy) (4.4.1)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas->statsbombpy) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->statsbombpy) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->statsbombpy) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->statsbombpy) (2025.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->statsbombpy) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->statsbombpy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->statsbombpy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->statsbombpy) (2024.12.14)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.11/dist-packages (from requests-cache->statsbombpy) (25.1.0)
Collecting cattrs>=22.2 (from requests-cache->statsbombpy)
  Downloading cattrs-24.1.2-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests-cache->statsbombpy) (4.3.6)
Collecting url-normalize>=1.4 (from requests-cache->statsbombpy)
  Downloading url_normalize-1.4.3-py2.py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->statsbombpy) (1.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from typeguard>=4.0.1->inflect->statsbombpy) (4.12.2)
Downloading statsbombpy-1.14.0-py3-none-any.whl (16 kB)
Downloading requests_cache-1.2.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.4/61.4 kB 1.6 MB/s eta 0:00:00
Downloading cattrs-24.1.2-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 4.3 MB/s eta 0:00:00
Downloading url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, statsbombpy
Successfully installed cattrs-24.1.2 requests-cache-1.2.1 statsbombpy-1.14.0 url-normalize-1.4.3

In [ ]:
from statsbombpy import sb
import pandas as pd
import numpy as np

In [ ]:
import warnings

# Ignore specific warning
warnings.filterwarnings("ignore", category=UserWarning, module="statsbombpy.api_client")

In [ ]:
# max row and column
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [ ]:
comps = sb.competitions()

In [ ]:
comps

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-07-15T14:15:54.671676,2024-07-15T14:17:00.877356,2024-07-15T14:17:00.877356,2024-07-15T14:15:54.671676
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-06-13T07:51:02.452825,None,None,2024-06-13T07:51:02.452825
3,16,4,Europe,Champions League,male,False,False,2018/2019,2024-06-12T07:44:38.559714,2021-06-13T16:17:31.694,None,2024-06-12T07:44:38.559714
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
5,16,2,Europe,Champions League,male,False,False,2016/2017,2024-02-13T02:37:32.205154,2021-06-13T16:17:31.694,None,2024-02-13T02:37:32.205154
6,16,27,Europe,Champions League,male,False,False,2015/2016,2024-06-12T07:45:38.786894,2021-06-13T16:17:31.694,None,2024-06-12T07:45:38.786894
7,16,26,Europe,Champions League,male,False,False,2014/2015,2024-02-12T12:49:54.914228,2021-06-13T16:17:31.694,None,2024-02-12T12:49:54.914228
8,16,25,Europe,Champions League,male,False,False,2013/2014,2024-02-12T12:48:48.479157,2021-06-13T16:17:31.694,None,2024-02-12T12:48:48.479157
9,16,24,Europe,Champions League,male,False,False,2012/2013,2024-02-12T12:47:34.340413,2021-06-13T16:17:31.694,None,2024-02-12T12:47:34.340413
10,16,23,Europe,Champions League,male,False,False,2011/2012,2024-02-13T02:36:35.698340,2021-06-13T16:17:31.694,None,2024-02-13T02:36:35.698340
11,16,22,Europe,Champions League,male,False,False,2010/2011,2024-02-12T12:53:03.944320,2021-06-13T16:17:31.694,None,2024-02-12T12:53:03.944320
12,16,21,Europe,Champions League,male,False,False,2009/2010,2024-02-12T12:49:25.017694,2021-06-13T16:17:31.694,None,2024-02-12T12:49:25.017694
13,16,41,Europe,Champions League,male,False,False,2008/2009,2024-02-13T07:02:54.657056,2021-06-13T16:17:31.694,None,2024-02-13T07:02:54.657056
14,16,39,Europe,Champions League,male,False,False,2006/2007,2024-02-12T13:48:23.967222,2021-06-13T16:17:31.694,None,2024-02-12T13:48:23.967222
15,16,37,Europe,Champions League,male,False,False,2004/2005,2024-02-12T13:09:19.665986,2021-06-13T16:17:31.694,None,2024-02-12T13:09:19.665986
16,16,44,Europe,Champions League,male,False,False,2003/2004,2024-02-12T13:51:22.366380,2021-06-13T16:17:31.694,None,2024-02-12T13:51:22.366380
17,16,76,Europe,Champions League,male,False,False,1999/2000,2020-07-29T05:00,2021-06-13T16:17:31.694,None,2020-07-29T05:00
18,16,277,Europe,Champions League,male,False,False,1972/1973,2024-02-13T14:25:16.532771,None,None,2024-02-13T14:25:16.532771
19,16,71,Europe,Champions League,male,False,False,1971/1972,2024-02-12T14:25:01.735880,2021-06-13T16:17:31.694,None,2024-02-12T14:25:01.735880
20,16,276,Europe,Champions League,male,False,False,1970/1971,2024-02-13T14:24:12.213582,None,None,2024-02-13T14:24:12.213582
21,223,282,South America,Copa America,male,False,True,2024,2024-07-15T18:00:33.653673,None,None,2024-07-15T18:00:33.653673
22,87,84,Spain,Copa del Rey,male,False,False,1983/1984,2024-02-13T01:54:12.946985,2021-06-13T16:17:31.694,None,2024-02-13T01:54:12.946985
23,87,268,Spain,Copa del Rey,male,False,False,1982/1983,2024-02-13T14:19:57.954551,None,None,2024-02-13T14:19:57.954551
24,87,279,Spain,Copa del Rey,male,False,False,1977/1978,2024-02-13T14:26:19.978418,None,None,2024-02-13T14:26:19.978418
25,37,90,England,FA Women's Super League,female,False,False,2020/2021,2023-02-25T14:52:09.326729,2021-06-13T16:17:31.694,None,2023-02-25T14:52:09.326729
26,37,42,England,FA Women's Super League,female,False,False,2019/2020,2024-02-12T15:05:34.211400,2021-06-13T16:17:31.694,None,2024-02-12T15:05:34.211400
27,37,4,England,FA Women's Super League,female,False,False,2018/2019,2024-06-12T07:41:45.347457,2021-06-13T16:17:31.694,None,2024-06-12T07:41:45.347457
28,1470,274,International,FIFA U20 World Cup,male,False,False,1979,2024-02-13T14:20:59.825440,None,None,2024-02-13T14:20:59.825440
29,43,106,International,FIFA World Cup,male,False,True,2022,2024-05-15T10:23:32.854925,2024-06-11T11:30:50.462448,2024-06-11T11:30:50.462448,2024-05-15T10:23:32.854925
30,43,3,International,FIFA World Cup,male,False,True,2018,2024-06-12T07:38:19.345758,2021-06-13T16:17:31.694,None,2024-06-12T07:38:19.345758
31,43,55,International,FIFA World Cup,male,False,True,1990,2023-06-28T10:58:20.137929,2021-06-12T16:17:31.694,None,2023-06-28T10:58:20.137929
32,43,54,International,FIFA World Cup,male,False,True,1986,2023-12-26T22:34:04.263530,2021-06-13T16:17:31.694,None,2023-12-26T22:34:04.263530
33,43,51,International,FIFA World Cup,male,False,True,1974,2024-02-13T02:52:29.582599,2021-06-13T16:17:31.694,None,2024-02-13T02:52:29.582599
34,43,272,International,FIFA World Cup,male,False,True,1970,2024-02-13T14:23:06.735299,None,None,2024-02-13T14:23:06.735299
35,43,270,International,FIFA World Cup,male,False,True,1962,2023-06-26T10:38:00.323984,None,None,2023-06-26T10:38:00.323984
36,43,269,International,FIFA World Cup,male,False,True,1958,2024-02-13T14:22:08.222297,None,None,2024-02-13T14:22:08.222297
37,1238,108,India,Indian Super league,male,False,False,2021/2022,2024-02-12T17:41:31.729787,None,None,2024-02-12T17:41:31.729787
38,11,90,Spain,La Liga,male,False,False,2020/2021,2024-07-15T15:15:28.367546,2024-07-15T15:17:45.455234,2024-07-15T15:17:45.455234,2024-07-15T15:15:28.367546
39,11,42,Spain,La Liga,male,False,False,2019/2020,2024-07-12T16:27:54.561817,2021-06-13T16:17:31.694,None,2024-07-12T16:27:54.561817
40,11,4,Spain,La Liga,male,False,False,2018/2019,2024-06-12T07:42:36.910303,2021-07-09T14:53:22.103024,None,2024-06-12T07:42:36.910303
41,11,1,Spain,La Liga,male,False,False,2017/2018,2024-06-12T07:32:43.196678,2021-06-13T16:17:31.694,None,2024-06-12T07:32:43.196678
42,11,2,Spain,La Liga,male,False,False,2016/2017,2024-03-12T08:49:46.449084,2021-06-13T16:17:31.694,None,2024-03-12T08:49:46.449084
43,11,27,Spain,La Liga,male,False,False,2015/2016,2024-05-16T14:06:52.149840,2021-06-13T16:17:31.694,None,2024-05-16T14:06:52.149840
44,11,26,Spain,La Liga,male,False,False,2014/2015,2023-09-20T17:22:28.925900,2021-06-13T16:17:31.694,None,2023-09-20T17:22:28.925900
45,11,25,Spain,La Liga,male,False,False,2013/2014,2022-07-23T12:18:49.547396,2021-06-13T16:17:31.694,None,2022-07-23T12:18:49.547396
46,11,24,Spain,La Liga,male,False,False,2012/2013,2024-03-10T11:24:05.201066,2021-06-13T16:17:31.694,None,2024-03-10T11:24:05.201066
47,11,23,Spain,La Liga,male,False,False,2011/2012,2022-12-01T14:10:17.791769,2021-06-13T16:17:31.694,None,2022-12-01T14:10:17.791769
48,11,22,Spain,La Liga,male,False,False,2010/2011,2023-04-19T10:48:44.079830,2021-06-13T16:17:31.694,None,2023-04-19T10:48:44.079830
49,11,21,Spain,La Liga,male,False,False,2009/2010,2023-11-29T10:55:10.039117,2021-06-13T16:17:31.694,None,2023-11-29T10:55:10.039117
50,11,41,Spain,La Liga,male,False,False,2008/2009,2023-04-19T10:46:29.203565,2021-06-13T16:17:31.694,None,2023-04-19T10:46:29.203565
51,11,40,Spain,La Liga,male,False,False,2007/2008,2023-04-19T10:42:35.284291,2021-06-13T16:17:31.694,None,2023-04-19T10:42:35.284291
52,11,39,Spain,La Liga,male,False,False,2006/2007,2023-03-26T23:19:39.125951,2021-06-13T16:17:31.694,None,2023-03-26T23:19:39.125951
53,11,38,Spain,La Liga,male,False,False,2005/2006,2022-07-03T12:34:31.749038,2021-06-13T16:17:31.694,None,2022-07-03T12:34:31.749038
54,11,37,Spain,La Liga,male,False,False,2004/2005,2023-11-29T10:56:10.031508,2021-06-13T16:17:31.694,None,2023-11-29T10:56:10.031508
55,11,278,Spain,La Liga,male,False,False,1973/1974,2023-07-06T12:50:48.807820,None,None,2023-07-06T12:50:48.807820
56,81,48,Argentina,Liga Profesional,male,False,False,1997/1998,2023-06-28T11:19:54.593488,None,None,2023-06-28T11:19:54.593488
57,81,275,Argentina,Liga Profesional,male,False,False,1981,2023-12-05T14:19:40.272816,None,None,2023-12-05T14:19:40.272816
58,7,235,France,Ligue 1,male,False,False,2022/2023,2024-06-11T00:50:53.277411,2024-06-26T08:17:36.043856,2024-06-26T08:17:36.043856,2024-06-11T00:50:53.277411
59,7,108,France,Ligue 1,male,False,False,2021/2022,2024-06-03T16:46:00.665854,2024-06-03T16:49:55.355195,2024-06-03T16:49:55.355195,2024-06-03T16:46:00.665854
60,7,27,France,Ligue 1,male,False,False,2015/2016,2024-01-07T06:23:44.277971,None,None,2024-01-07T06:23:44.277971
61,44,107,United States of America,Major League Soccer,male,False,False,2023,2024-07-14T18:53:28.735163,2024-07-14T18:58:42.974543,2024-07-14T18:58:42.974543,2024-07-14T18:53:28.735163
62,116,68,North and Central America,North American League,male,False,False,1977,2024-02-12T14:20:24.769832,2021-06-13T16:17:31.694,None,2024-02-12T14:20:24.769832
63,49,3,United States of America,NWSL,female,False,False,2018,2023-07-24T13:01:22.094587,2021-06-13T16:17:31.694,None,2023-07-24T13:01:22.094587
64,2,27,England,Premier League,male,False,False,2015/2016,2024-06-12T07:43:56.243851,2021-06-13T16:17:31.694,None,2024-06-12T07:43:56.243851
65,2,44,England,Premier League,male,False,False,2003/2004,2024-03-08T14:49:13.195793,2021-06-13T16:17:31.694,None,2024-03-08T14:49:13.195793
66,12,27,Italy,Serie A,male,False,False,2015/2016,2024-06-25T23:56:11.910924,None,None,2024-06-25T23:56:11.910924
67,12,86,Italy,Serie A,male,False,False,1986/1987,2023-06-18T01:55:53.343752,None,None,2023-06-18T01:55:53.343752
68,55,282,Europe,UEFA Euro,male,False,True,2024,2024-07-15T15:48:50.315500,2024-07-15T15:52:24.778809,2024-07-15T15:52:24.778809,2024-07-15T15:48:50.315500
69,55,43,Europe,UEFA Euro,male,False,True,2020,2024-04-16T12:44:40.558402,2024-04-16T12:47:18.505110,2024-04-16T12:47:18.505110,2024-04-16T12:44:40.558402
70,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2024-02-12T14:45:05.702250,2021-06-13T16:17:31.694,None,2024-02-12T14:45:05.702250
71,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2024-02-13T13:27:17.178263,2024-02-13T13:30:52.820588,2024-02-13T13:30:52.820588,2024-02-13T13:27:17.178263
72,72,107,International,Women's World Cup,female,False,True,2023,2024-07-14T16:59:48.469596,2024-07-14T17:01:38.887279,2024-07-14T17:01:38.887279,2024-07-14T16:59:48.469596
73,72,30,International,Women's World Cup,female,False,True,2019,2024-02-13T09:41:26.379767,2021-06-13T16:17:31.694,None,2024-02-13T09:41:26.379767

In [ ]:
comps = comps[comps.competition_gender == 'male'].reset_index(drop=True)
comps = comps.drop(index=[2, 18,19,20, 22,23,24, 25,28,29,30,31,32,33, 34, 52,53,54, 58,59, 66])

In [ ]:
comps.reset_index(drop=True, inplace=True)

In [ ]:
comps = comps.drop(index=[1,17,31,32,33,34,35,36,37,38,39,41,43])

In [ ]:
comps.reset_index(drop=True, inplace=True)

In [ ]:
comps

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-07-15T14:15:54.671676,2024-07-15T14:17:00.877356,2024-07-15T14:17:00.877356,2024-07-15T14:15:54.671676
1,16,4,Europe,Champions League,male,False,False,2018/2019,2024-06-12T07:44:38.559714,2021-06-13T16:17:31.694,None,2024-06-12T07:44:38.559714
2,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
3,16,2,Europe,Champions League,male,False,False,2016/2017,2024-02-13T02:37:32.205154,2021-06-13T16:17:31.694,None,2024-02-13T02:37:32.205154
4,16,27,Europe,Champions League,male,False,False,2015/2016,2024-06-12T07:45:38.786894,2021-06-13T16:17:31.694,None,2024-06-12T07:45:38.786894
5,16,26,Europe,Champions League,male,False,False,2014/2015,2024-02-12T12:49:54.914228,2021-06-13T16:17:31.694,None,2024-02-12T12:49:54.914228
6,16,25,Europe,Champions League,male,False,False,2013/2014,2024-02-12T12:48:48.479157,2021-06-13T16:17:31.694,None,2024-02-12T12:48:48.479157
7,16,24,Europe,Champions League,male,False,False,2012/2013,2024-02-12T12:47:34.340413,2021-06-13T16:17:31.694,None,2024-02-12T12:47:34.340413
8,16,23,Europe,Champions League,male,False,False,2011/2012,2024-02-13T02:36:35.698340,2021-06-13T16:17:31.694,None,2024-02-13T02:36:35.698340
9,16,22,Europe,Champions League,male,False,False,2010/2011,2024-02-12T12:53:03.944320,2021-06-13T16:17:31.694,None,2024-02-12T12:53:03.944320
10,16,21,Europe,Champions League,male,False,False,2009/2010,2024-02-12T12:49:25.017694,2021-06-13T16:17:31.694,None,2024-02-12T12:49:25.017694
11,16,41,Europe,Champions League,male,False,False,2008/2009,2024-02-13T07:02:54.657056,2021-06-13T16:17:31.694,None,2024-02-13T07:02:54.657056
12,16,39,Europe,Champions League,male,False,False,2006/2007,2024-02-12T13:48:23.967222,2021-06-13T16:17:31.694,None,2024-02-12T13:48:23.967222
13,16,37,Europe,Champions League,male,False,False,2004/2005,2024-02-12T13:09:19.665986,2021-06-13T16:17:31.694,None,2024-02-12T13:09:19.665986
14,16,44,Europe,Champions League,male,False,False,2003/2004,2024-02-12T13:51:22.366380,2021-06-13T16:17:31.694,None,2024-02-12T13:51:22.366380
15,16,76,Europe,Champions League,male,False,False,1999/2000,2020-07-29T05:00,2021-06-13T16:17:31.694,None,2020-07-29T05:00
16,43,106,International,FIFA World Cup,male,False,True,2022,2024-05-15T10:23:32.854925,2024-06-11T11:30:50.462448,2024-06-11T11:30:50.462448,2024-05-15T10:23:32.854925
17,43,3,International,FIFA World Cup,male,False,True,2018,2024-06-12T07:38:19.345758,2021-06-13T16:17:31.694,None,2024-06-12T07:38:19.345758
18,11,90,Spain,La Liga,male,False,False,2020/2021,2024-07-15T15:15:28.367546,2024-07-15T15:17:45.455234,2024-07-15T15:17:45.455234,2024-07-15T15:15:28.367546
19,11,42,Spain,La Liga,male,False,False,2019/2020,2024-07-12T16:27:54.561817,2021-06-13T16:17:31.694,None,2024-07-12T16:27:54.561817
20,11,4,Spain,La Liga,male,False,False,2018/2019,2024-06-12T07:42:36.910303,2021-07-09T14:53:22.103024,None,2024-06-12T07:42:36.910303
21,11,1,Spain,La Liga,male,False,False,2017/2018,2024-06-12T07:32:43.196678,2021-06-13T16:17:31.694,None,2024-06-12T07:32:43.196678
22,11,2,Spain,La Liga,male,False,False,2016/2017,2024-03-12T08:49:46.449084,2021-06-13T16:17:31.694,None,2024-03-12T08:49:46.449084
23,11,26,Spain,La Liga,male,False,False,2014/2015,2023-09-20T17:22:28.925900,2021-06-13T16:17:31.694,None,2023-09-20T17:22:28.925900
24,11,25,Spain,La Liga,male,False,False,2013/2014,2022-07-23T12:18:49.547396,2021-06-13T16:17:31.694,None,2022-07-23T12:18:49.547396
25,11,24,Spain,La Liga,male,False,False,2012/2013,2024-03-10T11:24:05.201066,2021-06-13T16:17:31.694,None,2024-03-10T11:24:05.201066
26,11,23,Spain,La Liga,male,False,False,2011/2012,2022-12-01T14:10:17.791769,2021-06-13T16:17:31.694,None,2022-12-01T14:10:17.791769
27,11,22,Spain,La Liga,male,False,False,2010/2011,2023-04-19T10:48:44.079830,2021-06-13T16:17:31.694,None,2023-04-19T10:48:44.079830
28,55,282,Europe,UEFA Euro,male,False,True,2024,2024-07-15T15:48:50.315500,2024-07-15T15:52:24.778809,2024-07-15T15:52:24.778809,2024-07-15T15:48:50.315500
29,55,43,Europe,UEFA Euro,male,False,True,2020,2024-04-16T12:44:40.558402,2024-04-16T12:47:18.505110,2024-04-16T12:47:18.505110,2024-04-16T12:44:40.558402

In [ ]:
all_shots = pd.DataFrame()
for i in comps.index:
    competition_id = comps['competition_id'][i]
    season_id = comps['season_id'][i]
    matches_ = sb.matches(competition_id = competition_id, season_id = season_id)
    print(f"Index: {i}, Comp_ID: {competition_id}, Match Count: {matches_.index.size}")
    for j in matches_.index:
        match_id = matches_['match_id'][j]
        events = sb.events(match_id = match_id)
        shots = events[events['type'] == 'Shot'].reset_index(drop=True)
        all_shots = pd.concat([all_shots, shots])

Index: 0, Comp_ID: 9, Match Count: 34
Index: 1, Comp_ID: 16, Match Count: 1
Index: 2, Comp_ID: 16, Match Count: 1
Index: 3, Comp_ID: 16, Match Count: 1
Index: 4, Comp_ID: 16, Match Count: 1
Index: 5, Comp_ID: 16, Match Count: 1
Index: 6, Comp_ID: 16, Match Count: 1
Index: 7, Comp_ID: 16, Match Count: 1
Index: 8, Comp_ID: 16, Match Count: 1
Index: 9, Comp_ID: 16, Match Count: 1
Index: 10, Comp_ID: 16, Match Count: 1
Index: 11, Comp_ID: 16, Match Count: 1
Index: 12, Comp_ID: 16, Match Count: 1
Index: 13, Comp_ID: 16, Match Count: 1
Index: 14, Comp_ID: 16, Match Count: 1
Index: 15, Comp_ID: 16, Match Count: 1
Index: 16, Comp_ID: 43, Match Count: 64
Index: 17, Comp_ID: 43, Match Count: 64
Index: 18, Comp_ID: 11, Match Count: 35
Index: 19, Comp_ID: 11, Match Count: 33
Index: 20, Comp_ID: 11, Match Count: 34
Index: 21, Comp_ID: 11, Match Count: 36
Index: 22, Comp_ID: 11, Match Count: 34
Index: 23, Comp_ID: 11, Match Count: 38
Index: 24, Comp_ID: 11, Match Count: 31
Index: 25, Comp_ID: 11, Match Count: 32
Index: 26, Comp_ID: 11, Match Count: 37
Index: 27, Comp_ID: 11, Match Count: 33
Index: 28, Comp_ID: 55, Match Count: 51
Index: 29, Comp_ID: 55, Match Count: 51

In [ ]:
all_shots.to_csv('all_shots_from_all_comps.csv', index=False)

In [ ]:
# adı UEFA Euro olan ve season'u 2024 olan competition'ın competition idsi ve season idsini al
euro24 = comps[(comps['competition_name'] == 'UEFA Euro') & (comps['season_name'] == '2024')]
euro24_competition_id = euro24['competition_id'].values[0]
euro24_season_id = euro24['season_id'].values[0]

euro24matches = sb.matches(competition_id = euro24_competition_id, season_id = euro24_season_id)

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3942819,2024-07-10,22:00:00.000,Europe - UEFA Euro,2024,Netherlands,England,1,2,available,available,2024-07-15T07:54:23.583297,2024-07-15T07:57:36.684453,6,Semi-finals,Signal-Iduna-Park,Felix Zwayer,Ronald Koeman,Gareth Southgate,1.1.0,2,2
1,3943043,2024-07-14,22:00:00.000,Europe - UEFA Euro,2024,Spain,England,2,1,available,available,2024-07-15T15:48:50.315500,2024-07-15T15:52:24.778809,7,Final,Olympiastadion Berlin,François Letexier,Luis de la Fuente Castillo,Gareth Southgate,1.1.0,2,2
2,3942752,2024-07-09,22:00:00.000,Europe - UEFA Euro,2024,Spain,France,2,1,available,available,2024-07-10T08:51:07.032303,2024-07-10T13:01:26.597509,6,Semi-finals,Allianz Arena,Slavko Vinčić,Luis de la Fuente Castillo,Didier Deschamps,1.1.0,2,2
3,3942382,2024-07-06,22:00:00.000,Europe - UEFA Euro,2024,Netherlands,Turkey,2,1,available,available,2024-07-10T06:50:04.068615,2024-07-10T06:56:35.146850,5,Quarter-finals,Olympiastadion Berlin,Clément Turpin,Ronald Koeman,Vincenzo Montella,1.1.0,2,2
4,3942349,2024-07-05,22:00:00.000,Europe - UEFA Euro,2024,Portugal,France,0,0,available,available,2024-07-12T01:57:15.210934,2024-07-12T02:00:16.871522,5,Quarter-finals,Volksparkstadion,Michael Oliver,Roberto Martínez Montoliú,Didier Deschamps,1.1.0,2,2
5,3930180,2024-06-25,19:00:00.000,Europe - UEFA Euro,2024,Netherlands,Austria,2,3,available,available,2024-07-11T13:24:55.422159,2024-07-11T13:25:37.289456,3,Group Stage,Olympiastadion Berlin,Ivan Kružliak,Ronald Koeman,Ralf Rangnick,1.1.0,2,2
6,3930171,2024-06-20,19:00:00.000,Europe - UEFA Euro,2024,Denmark,England,1,1,available,available,2024-07-12T05:16:00.445930,2024-07-12T05:19:44.572914,2,Group Stage,Deutsche Bank Park,Artur Manuel Ribeiro Soares Dias,Kasper Hjulmand,Gareth Southgate,1.1.0,2,2
7,3942227,2024-07-06,19:00:00.000,Europe - UEFA Euro,2024,England,Switzerland,1,1,available,available,2024-07-14T15:55:52.682165,2024-07-14T15:57:51.414762,5,Quarter-finals,Merkur Spiel-Arena,Daniele Orsato,Gareth Southgate,Murat Yakin,1.1.0,2,2
8,3942226,2024-07-05,19:00:00.000,Europe - UEFA Euro,2024,Spain,Germany,2,1,available,available,2024-07-13T03:52:05.176875,2024-07-13T03:52:43.383929,5,Quarter-finals,MHPArena,Anthony Taylor,Luis de la Fuente Castillo,Julian Nagelsmann,1.1.0,2,2
9,3938645,2024-06-26,19:00:00.000,Europe - UEFA Euro,2024,Ukraine,Belgium,0,0,available,available,2024-07-11T16:13:10.603169,2024-07-11T16:17:18.090189,3,Group Stage,MHPArena,Anthony Taylor,Sergiy Rebrov,Domenico Tedesco,1.1.0,2,2
10,3930184,2024-06-26,22:00:00.000,Europe - UEFA Euro,2024,Czech Republic,Turkey,1,2,available,available,2024-07-10T11:02:46.751020,2024-07-10T11:03:55.105146,3,Group Stage,Volksparkstadion,István Kovács,Ivan Hašek,Vincenzo Montella,1.1.0,2,2
11,3941022,2024-07-02,22:00:00.000,Europe - UEFA Euro,2024,Austria,Turkey,1,2,available,available,2024-07-10T11:29:53.368810,2024-07-10T11:31:13.553408,4,Round of 16,Red Bull Arena,Artur Manuel Ribeiro Soares Dias,Ralf Rangnick,Vincenzo Montella,1.1.0,2,2
12,3941021,2024-07-02,19:00:00.000,Europe - UEFA Euro,2024,Romania,Netherlands,0,3,available,available,2024-07-12T23:26:38.304669,2024-07-12T23:28:27.122555,4,Round of 16,Allianz Arena,Felix Zwayer,Edward Iordănescu,Ronald Koeman,1.1.0,2,2
13,3941020,2024-07-01,22:00:00.000,Europe - UEFA Euro,2024,Portugal,Slovenia,0,0,available,available,2024-07-13T19:48:26.863138,2024-07-13T19:48:57.256302,4,Round of 16,Deutsche Bank Park,Daniele Orsato,Roberto Martínez Montoliú,Matjaž Kek,1.1.0,2,2
14,3941019,2024-07-01,19:00:00.000,Europe - UEFA Euro,2024,France,Belgium,1,0,available,available,2024-07-10T11:03:34.307124,2024-07-10T11:04:16.590488,4,Round of 16,Merkur Spiel-Arena,Glenn Nyberg,Didier Deschamps,Domenico Tedesco,1.1.0,2,2
15,3941018,2024-06-30,22:00:00.000,Europe - UEFA Euro,2024,Spain,Georgia,4,1,available,available,2024-07-12T06:06:58.963038,2024-07-12T06:08:12.572176,4,Round of 16,RheinEnergieStadion,François Letexier,Luis de la Fuente Castillo,Willy Sagnol,1.1.0,2,2
16,3941017,2024-06-30,19:00:00.000,Europe - UEFA Euro,2024,England,Slovakia,2,1,available,available,2024-07-10T11:29:00.136519,2024-07-10T11:31:44.852038,4,Round of 16,VELTINS-Arena,Halil Umut Meler,Gareth Southgate,Francesco Calzona,1.1.0,2,2
17,3930182,2024-06-25,22:00:00.000,Europe - UEFA Euro,2024,Denmark,Serbia,0,0,available,available,2024-07-10T09:18:43.407808,2024-07-10T09:19:06.030329,3,Group Stage,Allianz Arena,François Letexier,Kasper Hjulmand,Dragan Stojković,1.1.0,2,2
18,3930179,2024-06-24,22:00:00.000,Europe - UEFA Euro,2024,Albania,Spain,0,1,available,available,2024-07-01T06:01:14.238710,2024-07-01T06:07:22.418137,3,Group Stage,Merkur Spiel-Arena,Glenn Nyberg,Sylvio Mendes Campos Junior,Luis de la Fuente Castillo,1.1.0,2,2
19,3940983,2024-06-29,22:00:00.000,Europe - UEFA Euro,2024,Germany,Denmark,2,0,available,available,2024-07-07T11:13:23.042917,2024-07-07T11:16:18.087539,4,Round of 16,Signal-Iduna-Park,Michael Oliver,Julian Nagelsmann,Kasper Hjulmand,1.1.0,2,2
20,3940878,2024-06-29,19:00:00.000,Europe - UEFA Euro,2024,Switzerland,Italy,2,0,available,available,2024-07-12T01:31:40.240029,2024-07-12T01:32:19.577126,4,Round of 16,Olympiastadion Berlin,Szymon Marciniak,Murat Yakin,Luciano Spalletti,1.1.0,2,2
21,3930177,2024-06-23,22:00:00.000,Europe - UEFA Euro,2024,Scotland,Hungary,0,1,available,available,2024-07-10T14:53:58.833786,2024-07-10T14:56:29.359087,3,Group Stage,MHPArena,Facundo Tello Figueroa,Steve Clarke,Marco Rossi,1.1.0,2,2
22,3930173,2024-06-21,22:00:00.000,Europe - UEFA Euro,2024,Netherlands,France,0,0,available,available,2024-07-12T19:37:47.584481,2024-07-12T19:39:43.381031,2,Group Stage,Trainingszentrum RB Leipzig Platz 1,Anthony Taylor,Ronald Koeman,Didier Deschamps,1.1.0,2,2
23,3930172,2024-06-20,22:00:00.000,Europe - UEFA Euro,2024,Spain,Italy,1,0,available,available,2024-07-12T00:15:20.599402,2024-07-12T00:16:51.275112,2,Group Stage,VELTINS-Arena,Slavko Vinčić,Luis de la Fuente Castillo,Luciano Spalletti,1.1.0,2,2
24,3930167,2024-06-19,16:00:00.000,Europe - UEFA Euro,2024,Croatia,Albania,2,2,available,available,2024-07-11T08:16:46.595970,2024-07-11T08:18:46.582123,2,Group Stage,Volksparkstadion,François Letexier,Zlatko Dalić,Sylvio Mendes Campos Junior,1.1.0,2,2
25,3930168,2024-06-19,19:00:00.000,Europe - UEFA Euro,2024,Germany,Hungary,2,0,available,available,2024-07-11T14:19:14.279155,2024-07-11T14:24:30.771631,2,Group Stage,MHPArena,Danny Desmond Makkelie,Julian Nagelsmann,Marco Rossi,1.1.0,2,2
26,3930165,2024-06-17,22:00:00.000,Europe - UEFA Euro,2024,Austria,France,0,1,available,available,2024-07-13T18:17:49.004138,2024-07-13T18:19:14.500227,1,Group Stage,Merkur Spiel-Arena,Jesús Gil Manzano,Ralf Rangnick,Didier Deschamps,1.1.0,2,2
27,3930164,2024-06-17,19:00:00.000,Europe - UEFA Euro,2024,Belgium,Slovakia,0,1,available,available,2024-07-13T23:57:02.143146,2024-07-14T00:00:18.546176,1,Group Stage,Deutsche Bank Park,Halil Umut Meler,Domenico Tedesco,Francesco Calzona,1.1.0,2,2
28,3930161,2024-06-15,22:00:00.000,Europe - UEFA Euro,2024,Italy,Albania,2,1,available,available,2024-07-12T05:15:04.821436,2024-07-12T05:16:16.043874,1,Group Stage,Signal-Iduna-Park,Felix Zwayer,Luciano Spalletti,Sylvio Mendes Campos Junior,1.1.0,2,2
29,3938637,2024-06-16,16:00:00.000,Europe - UEFA Euro,2024,Poland,Netherlands,1,2,available,available,2024-07-12T03:37:17.747730,2024-07-12T03:39:53.010211,1,Group Stage,Volksparkstadion,Artur Manuel Ribeiro Soares Dias,Michał Probierz,Ronald Koeman,1.1.0,2,2
30,3938640,2024-06-21,16:00:00.000,Europe - UEFA Euro,2024,Slovakia,Ukraine,1,2,available,available,2024-07-12T18:52:43.723907,2024-07-12T18:56:00.519961,2,Group Stage,Merkur Spiel-Arena,Michael Oliver,Francesco Calzona,Sergiy Rebrov,1.1.0,2,2
31,3938642,2024-06-22,16:00:00.000,Europe - UEFA Euro,2024,Georgia,Czech Republic,1,1,available,available,2024-07-09T12:50:20.740381,2024-07-09T12:53:31.025418,2,Group Stage,Volksparkstadion,Daniel Siebert,Willy Sagnol,Ivan Hašek,1.1.0,2,2
32,3938639,2024-06-18,19:00:00.000,Europe - UEFA Euro,2024,Turkey,Georgia,3,1,available,available,2024-07-12T06:04:52.417134,2024-07-12T06:05:10.871017,1,Group Stage,Signal-Iduna-Park,Facundo Tello Figueroa,Vincenzo Montella,Willy Sagnol,1.1.0,2,2
33,3938641,2024-06-21,19:00:00.000,Europe - UEFA Euro,2024,Poland,Austria,1,3,available,available,2024-07-12T21:09:31.780785,2024-07-12T21:10:46.438024,2,Group Stage,Olympiastadion Berlin,Halil Umut Meler,Michał Probierz,Ralf Rangnick,1.1.0,2,2
34,3938644,2024-06-26,22:00:00.000,Europe - UEFA Euro,2024,Georgia,Portugal,2,0,available,available,2024-07-12T05:40:33.402849,2024-07-12T05:42:21.069872,3,Group Stage,VELTINS-Arena,Sandro Schärer,Willy Sagnol,Roberto Martínez Montoliú,1.1.0,2,2
35,3938643,2024-06-25,19:00:00.000,Europe - UEFA Euro,2024,France,Poland,1,1,available,available,2024-07-12T06:05:55.170896,2024-07-12T06:08:47.869486,3,Group Stage,Signal-Iduna-Park,Marco Guida,Didier Deschamps,Michał Probierz,1.1.0,2,2
36,3938638,2024-06-17,16:00:00.000,Europe - UEFA Euro,2024,Romania,Ukraine,3,0,available,available,2024-07-12T03:38:10.661840,2024-07-12T03:39:18.794242,1,Group Stage,Allianz Arena,Glenn Nyberg,Edward Iordănescu,Sergiy Rebrov,1.1.0,2,2
37,3930183,2024-06-26,19:00:00.000,Europe - UEFA Euro,2024,Slovakia,Romania,1,1,available,available,2024-07-09T16:08:41.246995,2024-07-09T16:16:22.181617,3,Group Stage,Deutsche Bank Park,Daniel Siebert,Francesco Calzona,Edward Iordănescu,1.1.0,2,2
38,3930181,2024-06-25,22:00:00.000,Europe - UEFA Euro,2024,England,Slovenia,0,0,available,available,2024-07-10T14:26:49.966712,2024-07-10T14:27:59.561474,3,Group Stage,RheinEnergieStadion,Clément Turpin,Gareth Southgate,Matjaž Kek,1.1.0,2,2
39,3930178,2024-06-24,22:00:00.000,Europe - UEFA Euro,2024,Croatia,Italy,1,1,available,available,2024-07-10T12:21:13.840986,2024-07-10T12:23:12.394850,3,Group Stage,Red Bull Arena,Danny Desmond Makkelie,Zlatko Dalić,Luciano Spalletti,1.1.0,2,2
40,3930176,2024-06-23,22:00:00.000,Europe - UEFA Euro,2024,Switzerland,Germany,1,1,available,available,2024-07-13T21:41:00.247826,2024-07-13T21:41:29.142800,3,Group Stage,Deutsche Bank Park,Daniele Orsato,Murat Yakin,Julian Nagelsmann,1.1.0,2,2
41,3930175,2024-06-22,22:00:00.000,Europe - UEFA Euro,2024,Belgium,Romania,2,0,available,available,2024-07-09T15:12:57.012326,2024-07-09T15:13:58.718506,2,Group Stage,RheinEnergieStadion,Szymon Marciniak,Domenico Tedesco,Edward Iordănescu,1.1.0,2,2
42,3930174,2024-06-22,19:00:00.000,Europe - UEFA Euro,2024,Turkey,Portugal,0,3,available,available,2024-07-11T16:39:20.496235,2024-07-11T16:43:45.852125,2,Group Stage,Signal-Iduna-Park,Felix Zwayer,Vincenzo Montella,Roberto Martínez Montoliú,1.1.0,2,2
43,3930170,2024-06-20,16:00:00.000,Europe - UEFA Euro,2024,Slovenia,Serbia,1,1,available,available,2024-07-12T18:51:51.416868,2024-07-12T18:53:31.866826,2,Group Stage,Allianz Arena,István Kovács,Matjaž Kek,Dragan Stojković,1.1.0,2,2
44,3930169,2024-06-19,22:00:00.000,Europe - UEFA Euro,2024,Scotland,Switzerland,1,1,available,available,2024-07-13T23:57:40.464361,2024-07-14T00:02:35.662811,2,Group Stage,RheinEnergieStadion,Ivan Kružliak,Steve Clarke,Murat Yakin,1.1.0,2,2
45,3930166,2024-06-18,22:00:00.000,Europe - UEFA Euro,2024,Portugal,Czech Republic,2,1,available,available,2024-07-10T14:53:09.929031,2024-07-10T14:54:55.319751,1,Group Stage,Red Bull Arena,Marco Guida,Roberto Martínez Montoliú,Ivan Hašek,1.1.0,2,2
46,3930163,2024-06-16,22:00:00.000,Europe - UEFA Euro,2024,Serbia,England,0,1,available,available,2024-07-14T07:08:44.634374,2024-07-14T07:10:41.937955,1,Group Stage,VELTINS-Arena,Daniele Orsato,Dragan Stojković,Gareth Southgate,1.1.0,2,2
47,3930162,2024-06-16,19:00:00.000,Europe - UEFA Euro,2024,Slovenia,Denmark,1,1,available,available,2024-07-10T16:07:00.970746,2024-07-10T16:09:27.468163,1,Group Stage,MHPArena,Sandro Schärer,Matjaž Kek,Kasper Hjulmand,1.1.0,2,2
48,3930160,2024-06-15,19:00:00.000,Europe - UEFA Euro,2024,Spain,Croatia,3,0,available,available,2024-07-12T03:36:29.899268,2024-07-12T03:40:20.513429,1,Group Stage,Olympiastadion Berlin,Michael Oliver,Luis de la Fuente Castillo,Zlatko Dalić,1.1.0,2,2
49,3930159,2024-06-15,16:00:00.000,Europe - UEFA Euro,2024,Hungary,Switzerland,1,3,available,available,2024-07-10T13:33:58.630908,2024-07-10T13:35:35.263551,1,Group Stage,RheinEnergieStadion,Slavko Vinčić,Marco Rossi,Murat Yakin,1.1.0,2,2
50,3930158,2024-06-14,22:00:00.000,Europe - UEFA Euro,2024,Germany,Scotland,5,1,available,available,2024-07-04T08:11:49.443397,2024-07-04T08:13:19.028344,1,Group Stage,Allianz Arena,Clément Turpin,Julian Nagelsmann,Steve Clarke,1.1.0,2,2